In [2]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.utils import to_categorical
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix

iris = load_iris()
X = iris.data
y = iris.target

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

num_classes = len(iris.target_names)
y_train_one_hot = to_categorical(y_train, num_classes=num_classes)
y_test_one_hot = to_categorical(y_test, num_classes=num_classes)

model = Sequential()
model.add(Dense(units=64, activation='relu', input_dim=X_train_scaled.shape[1]))
model.add(Dense(10, activation='relu'))
model.add(Dense(units=num_classes, activation='softmax'))

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

model.fit(X_train_scaled, y_train_one_hot, epochs=10, batch_size=32, validation_split=0.2)

Epoch 1/10
3/3 [==============================] - 2s 152ms/step - loss: 1.2332 - accuracy: 0.2500 - val_loss: 1.1453 - val_accuracy: 0.3750
Epoch 2/10
3/3 [==============================] - 0s 27ms/step - loss: 1.1732 - accuracy: 0.3125 - val_loss: 1.1004 - val_accuracy: 0.4167
Epoch 3/10
3/3 [==============================] - 0s 24ms/step - loss: 1.1184 - accuracy: 0.3958 - val_loss: 1.0605 - val_accuracy: 0.5833
Epoch 4/10
3/3 [==============================] - 0s 18ms/step - loss: 1.0653 - accuracy: 0.5208 - val_loss: 1.0279 - val_accuracy: 0.6667
Epoch 5/10
3/3 [==============================] - 0s 19ms/step - loss: 1.0217 - accuracy: 0.7188 - val_loss: 0.9966 - val_accuracy: 0.7500
Epoch 6/10
3/3 [==============================] - 0s 20ms/step - loss: 0.9810 - accuracy: 0.8125 - val_loss: 0.9670 - val_accuracy: 0.8333
Epoch 7/10
3/3 [==============================] - 0s 18ms/step - loss: 0.9401 - accuracy: 0.8229 - val_loss: 0.9384 - val_accuracy: 0.8333
Epoch 8/10
3/3 [==========

In [3]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 64)                320       
                                                                 
 dense_1 (Dense)             (None, 10)                650       
                                                                 
 dense_2 (Dense)             (None, 3)                 33        
                                                                 
Total params: 1,003
Trainable params: 1,003
Non-trainable params: 0
_________________________________________________________________


In [5]:
_, test_accuracy = model.evaluate(X_test_scaled, y_test_one_hot)
print("Test Accuracy:", test_accuracy)

y_pred = model.predict(X_test_scaled)
y_pred_classes = tf.argmax(y_pred, axis=1)

y_test = tf.argmax(y_test_one_hot, axis=1)

print("Classification Report:")
print(classification_report(y_test, y_pred_classes))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred_classes))

1/1 [==============================] - 0s 32ms/step - loss: 0.8234 - accuracy: 0.9333
Test Accuracy: 0.9333333373069763
1/1 [==============================] - 0s 23ms/step
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.89      0.89      0.89         9
           2       0.91      0.91      0.91        11

    accuracy                           0.93        30
   macro avg       0.93      0.93      0.93        30
weighted avg       0.93      0.93      0.93        30

Confusion Matrix:
[[10  0  0]
 [ 0  8  1]
 [ 0  1 10]]
