In [17]:
import tensorflow as tf
import numpy as np

m1= tf.constant([1,2,3,4],shape=[2,2])
m1

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [18]:
m2= tf.constant([7,8,9,10],shape=[2,2])
m2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10]])>

In [19]:
mmult=tf.matmul(m1,m2)
mmult

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[25, 28],
       [57, 64]])>

In [27]:
matrix = tf.constant([[1.0, 2.0, 3.0],
                      [4.0, 5.0, 6.0],
                      [7.0, 8.0, 9.0]])

# Compute eigenvalues and eigenvectors
eigenvalues, eigenvectors = tf.linalg.eig(matrix)

# Convert the eigenvalues and eigenvectors to NumPy arrays
eigenvalues_np = eigenvalues.numpy()
eigenvectors_np = eigenvectors.numpy()

print(eigenvalues_np)
print(eigenvectors_np)

[ 1.6116844e+01+0.j -1.1168439e+00+0.j -5.1728279e-07+0.j]
[[ 0.23197053+0.j  0.7858302 +0.j  0.40824813+0.j]
 [ 0.525322  +0.j  0.08675158+0.j -0.8164967 +0.j]
 [ 0.8186736 +0.j -0.6123275 +0.j  0.40824836+0.j]]
