In [3]:
import numpy as np
from keras.layers import Dense
from keras.models import Sequential

model=Sequential()
model.add(Dense(units=2,activation='relu',input_dim=2))
model.add(Dense(units=1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_2 (Dense)             (None, 2)                 6         
                                                                 
 dense_3 (Dense)             (None, 1)                 3         
                                                                 
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [4]:
model.get_weights()

[array([[ 0.9961654 , -0.45002085],
        [ 0.6621436 ,  0.33178806]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[ 0.47717822],
        [-0.96925104]], dtype=float32),
 array([0.], dtype=float32)]

In [6]:
X=np.array([[0.,0.],[0.,1.],[1.,0.],[1.,1.]])
Y=np.array([0.,1.,1.,0.])
model.fit(X,Y,epochs=100,batch_size=4)

Epoch 1/100
1/1 [==============================] - 2s 2s/step - loss: 0.7594 - accuracy: 0.5000
Epoch 2/100
1/1 [==============================] - 0s 6ms/step - loss: 0.7589 - accuracy: 0.5000
Epoch 3/100
1/1 [==============================] - 0s 5ms/step - loss: 0.7584 - accuracy: 0.5000
Epoch 4/100
1/1 [==============================] - 0s 15ms/step - loss: 0.7579 - accuracy: 0.5000
Epoch 5/100
1/1 [==============================] - 0s 0s/step - loss: 0.7573 - accuracy: 0.5000
Epoch 6/100
1/1 [==============================] - 0s 750us/step - loss: 0.7568 - accuracy: 0.5000
Epoch 7/100
1/1 [==============================] - 0s 17ms/step - loss: 0.7563 - accuracy: 0.5000
Epoch 8/100
1/1 [==============================] - 0s 16ms/step - loss: 0.7558 - accuracy: 0.5000
Epoch 9/100
1/1 [==============================] - 0s 0s/step - loss: 0.7553 - accuracy: 0.5000
Epoch 10/100
1/1 [==============================] - 0s 3ms/step - loss: 0.7548 - accuracy: 0.5000
Epoch 11/100
1/1 [=========

1/1 [==============================] - 0s 8ms/step - loss: 0.7234 - accuracy: 0.7500
Epoch 85/100
1/1 [==============================] - 0s 12ms/step - loss: 0.7230 - accuracy: 0.7500
Epoch 86/100
1/1 [==============================] - 0s 0s/step - loss: 0.7227 - accuracy: 0.7500
Epoch 87/100
1/1 [==============================] - 0s 3ms/step - loss: 0.7223 - accuracy: 0.7500
Epoch 88/100
1/1 [==============================] - 0s 15ms/step - loss: 0.7220 - accuracy: 0.7500
Epoch 89/100
1/1 [==============================] - 0s 0s/step - loss: 0.7217 - accuracy: 0.7500
Epoch 90/100
1/1 [==============================] - 0s 19ms/step - loss: 0.7213 - accuracy: 0.7500
Epoch 91/100
1/1 [==============================] - 0s 10ms/step - loss: 0.7210 - accuracy: 0.7500
Epoch 92/100
1/1 [==============================] - 0s 5ms/step - loss: 0.7207 - accuracy: 0.7500
Epoch 93/100
1/1 [==============================] - 0s 14ms/step - loss: 0.7203 - accuracy: 0.7500
Epoch 94/100
1/1 [============

In [7]:
model.get_weights()

[array([[ 0.90814555, -0.45002085],
        [ 0.5729896 ,  0.2335655 ]], dtype=float32),
 array([ 0.00011534, -0.09822253], dtype=float32),
 array([[ 0.38715184],
        [-0.8828731 ]], dtype=float32),
 array([-0.08984993], dtype=float32)]

In [8]:
model.predict(X,batch_size=4)

1/1 [==============================] - 0s 260ms/step


array([[0.47756374],
       [0.5031344 ],
       [0.565075  ],
       [0.6186021 ]], dtype=float32)